<?php

declare(strict_types=1);

use Yiisoft\Html\Html as H;
use Yiisoft\Translator\TranslatorInterface;
use Yiisoft\View\WebView;

/**
 * Placeholder Privacy Policy — OAuth/payment provider app-registration
 * dashboards commonly require a working URL here. Replace this content with
 * real legal text (or a proper policy generator's output) before production
 * use; this file exists so the route/page itself is never missing.
 *
 * @var WebView $this
 * @var TranslatorInterface $translator
 * @var string $contactEmail
 */
$this->setTitle('Privacy Policy');

$container = ['class' => 'container py-4'];

echo H::openTag('div', $container); //0
 echo H::openTag('h1'); //1
  echo H::encode($this->getTitle());
 echo H::closeTag('h1'); //1
 echo H::openTag('p', ['class' => 'text-muted']); //1
  echo 'This is placeholder content generated by the ddd-template starter kit —'
      . ' replace it with your own privacy policy before going to production.';
 echo H::closeTag('p'); //1
 echo H::openTag('h2'); //1
  echo 'What this app collects';
 echo H::closeTag('h2'); //1
 echo H::openTag('p'); //1
  echo 'Account data you provide at signup (login, email, hashed password),'
      . ' and, if you enable it, your Telegram chat id for bot notifications.'
      . ' Two-factor authentication secrets are stored to verify login codes.';
 echo H::closeTag('p'); //1
 echo H::openTag('h2'); //1
  echo 'Cookies';
 echo H::closeTag('h2'); //1
 echo H::openTag('p'); //1
  echo 'A session cookie keeps you signed in; an optional "remember me"'
      . ' cookie extends that across browser restarts. Both are strictly'
      . ' necessary for the site to function and carry no third-party tracking.';
 echo H::closeTag('p'); //1
 echo H::openTag('h2'); //1
  echo 'Contact';
 echo H::closeTag('h2'); //1
 echo H::openTag('p'); //1
  echo 'Questions about this policy: ' . H::encode($contactEmail);
 echo H::closeTag('p'); //1
echo H::closeTag('div'); //0
