<?php

declare(strict_types=1);

use Yiisoft\Html\Html as H;
use Yiisoft\Translator\TranslatorInterface;
use Yiisoft\View\WebView;

/**
 * Placeholder Terms of Service — same rationale as privacypolicy.php:
 * provider app-registration dashboards commonly require this URL to exist.
 * Replace with real terms before production use.
 *
 * @var WebView $this
 * @var TranslatorInterface $translator
 * @var string $contactEmail
 */
$this->setTitle('Terms of Service');

$container = ['class' => 'container py-4'];

echo H::openTag('div', $container); //0
 echo H::openTag('h1'); //1
  echo H::encode($this->getTitle());
 echo H::closeTag('h1'); //1
 echo H::openTag('p', ['class' => 'text-muted']); //1
  echo 'This is placeholder content generated by the ddd-template starter kit —'
      . ' replace it with your own terms of service before going to production.';
 echo H::closeTag('p'); //1
 echo H::openTag('h2'); //1
  echo 'Accounts';
 echo H::closeTag('h2'); //1
 echo H::openTag('p'); //1
  echo 'You are responsible for keeping your login credentials and'
      . ' two-factor authentication device secure. The first account created'
      . ' on a fresh install is automatically granted the administrator role.';
 echo H::closeTag('p'); //1
 echo H::openTag('h2'); //1
  echo 'Acceptable use';
 echo H::closeTag('h2'); //1
 echo H::openTag('p'); //1
  echo 'Do not use this service for unlawful purposes or in a way that'
      . ' disrupts it for other users.';
 echo H::closeTag('p'); //1
 echo H::openTag('h2'); //1
  echo 'Changes';
 echo H::closeTag('h2'); //1
 echo H::openTag('p'); //1
  echo 'These terms may change as the app evolves; continued use after a'
      . ' change means you accept the updated terms.';
 echo H::closeTag('p'); //1
 echo H::openTag('h2'); //1
  echo 'Contact';
 echo H::closeTag('h2'); //1
 echo H::openTag('p'); //1
  echo 'Questions about these terms: ' . H::encode($contactEmail);
 echo H::closeTag('p'); //1
echo H::closeTag('div'); //0
